// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCadastroProcessos.Data;

#nullable disable

namespace WebCadastroProcessos.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebCadastroProcessos.Models.Processo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataCadastro");

                    b.Property<DateTime>("DataVisualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataVisualizacao");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Municipio");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.Property<string>("Npu")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Npu");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Uf");

                    b.HasKey("Id");

                    b.ToTable("Processo");
                });
#pragma warning restore 612, 618
        }
    }
}
